name: Dev Release

on:
  push:
    paths-ignore:
      - '.devcontainer/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.vscode/**'
      - 'docs/**'
      - 'images/**'
      - 'schema/**'
      - 'README.md'
    branches:
      - dev

defaults:
  run:
    shell: bash

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
   #windows:
     #runs-on: windows-latest
 #
     #defaults:
       #run:
         #shell: bash
 #
     #steps:
       #- uses: actions/checkout@main
       #- name: Build
         #run: |
           #cargo build --release
       #- name: Test
         #run: |
           #cargo test \
             #--release \
             #--workspace \
             #--exclude espanso-modulo \
             #--exclude espanso-ipc \
             #--no-default-features \
             #--features native-tls
       #- name: Build resources
         #shell: pwsh
         #run: |
             #$env:EXEC_PATH = "target\release\espanso.exe"
             #scripts\build_windows_resources.ps1
       #- name: Build installer
         #shell: pwsh
         #run: |
             #Install-Module -Name 'PSTOML' -Force
             #scripts\build_windows_installer.ps1
       #- name: Build portable mode archive
         #shell: pwsh
         #run: |
             #scripts\build_windows_portable.ps1
       #- uses: actions/upload-artifact@main
         #name: "Upload artifacts"
         #with:
           #name: Windows Artifacts
           #path: |
             #target/windows/Espanso-Win-Installer-x86_64.exe
             #target/windows/espanso-win-portable-x86_64.zip
 #
   #linux-x11:
     #runs-on: ubuntu-latest
 #
     #steps:
       #- uses: actions/checkout@main
       #- name: install linux dependencies
         #run: |
           #sudo apt-get update
           #sudo apt-get install -y libx11-dev libxtst-dev libxkbcommon-dev libdbus-1-dev libwxgtk3.2-dev
       #- name: build docker image
         #run: |
           #sudo docker build -t espanso-ubuntu . -f .github/scripts/dockerfile
       #- name: build
         #run: |
           #cargo build \
             #-p espanso \
             #--release \
             #--no-default-features \
             #--features vendored-tls,modulo
       #- name: build appimage
         #run: |
           #sudo docker run \
             #--rm \
             #-v "$(pwd):/shared" \
             #espanso-ubuntu \
             #espanso/.github/scripts/ubuntu/build_appimage.sh
       #- uses: actions/upload-artifact@main
         #name: "upload artifacts"
         #with:
           #name: linux x11 appimage artifact
           #path: |
             #espanso-x11.appimage
 #
   #linux-deb:
     #runs-on: ubuntu-latest
 #
     #steps:
       #- uses: actions/checkout@main
       #- name: install linux dependencies
         #run: |
           #sudo apt-get update
           #sudo apt-get install -y libx11-dev libxtst-dev libxkbcommon-dev libdbus-1-dev libwxgtk3.2-dev
       #- name: build
         #run: |
           #cargo build \
             #-p espanso \
             #--release \
             #--no-default-features \
             #--features vendored-tls,modulo
       #- name: build docker image
         #run: |
           #sudo docker build -t espanso-ubuntu . -f .github/scripts/dockerfile
       #- name: build deb packages
         #run: |
           #sudo docker run --rm -v "$(pwd):/shared" espanso-ubuntu espanso/.github/scripts/ubuntu/build_deb.sh
       #- uses: actions/upload-artifact@main
         #name: "upload artifacts"
         #with:
           #name: linux deb artifacts
           #path: |
             #espanso-debian-x11-amd64.deb
             #espanso-debian-wayland-amd64.deb
 #
   #macos:
     #runs-on: macos-latest
 #
     #steps:
       #- uses: actions/checkout@main
       #- name: install rust target
         #run: |
           #rustup update
           #rustup target add aarch64-apple-darwin x86_64-apple-darwin
       #- name: test
         #run: |
           #cargo test \
             #-p espanso \
             #--target x86_64-apple-darwin \
             #--no-default-features \
             #--features native-tls,modulo
           #cargo test \
             #-p espanso \
             #--target aarch64-apple-darwin \
             #--no-default-features \
             #--features native-tls,modulo
       #- name: build
         #run: |
           #cargo build \
             #-p espanso \
             #--target x86_64-apple-darwin \
             #--release \
             #--no-default-features \
             #--features native-tls,modulo
           #cargo build \
             #-p espanso \
             #--target aarch64-apple-darwin \
             #--release \
             #--no-default-features \
             #--features native-tls,modulo
           #bash ./scripts/create_bundle.sh
       #- name: create zip archive
         #run: |
           #ditto -c -k --sequesterrsrc --keepparent target/mac/espanso.app espanso-mac-universal.zip
       #- uses: actions/upload-artifact@main
         #name: "upload artifacts"
         #with:
           #name: macos artifacts
           #path: |
             #espanso-mac-universal.zip

  snap:
    runs-on: ubuntu-latest
    outputs:
      snap-file: ${{ steps.build-snap.outputs.snap }}
    steps:
    - uses: actions/checkout@v4
    - uses: snapcore/action-build@v1
      id: build-snap
    - run: |
        sudo snap install --classic --dangerous ${{ steps.build-snap.outputs.snap }}
        #- uses: actions/upload-artifact@v4
        # with:
        #name: slapcat-espanso
        #path: ${{ steps.build-snap.outputs.snap }}
      #    - uses: actions/download-artifact@v4
      #      with:
        #        name: slapcat-espanso
    - uses: snapcore/action-publish@v1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
      with:
        snap: ${{needs.build-snap.outputs.snap-file}}
        release: ${{ startsWith(github.ref, 'refs/tags/') && 'candidate' || 'edge'}}
